name: random_color_generator
description: It is a single page app that displays random colors when you tap on the screen.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  solid_lints: ^0.0.18

flutter:
  uses-material-design: true